# Generated by Django 5.0.1 on 2024-02-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_remove_task_id_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.AutoField(default='some_default_value', primary_key=True, serialize=False),
        ),
    ]
